title: Tarcísio Fischer - Blog pessoal
email: tarcisio.fischer.cco@gmail.com
description: >-
  Tarcísio Fischer - Blog pessoal
baseurl: ""
url: "http://tarcisiofischer.github.io"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: tale
comments: true
permalink: /:year-:month-:day/:title
paginate: 5
plugins:
  - jekyll-feed

